
identity:
  name: test_get_range_values
  author: hn_big_volibear
  label:
    en_US: test_get_range_values
    zh_Hans: 【读写类】读取区域值
    pt_BR: test_get_range_values
description:
  human:
    en_US: test_get_range_values
    zh_Hans: 【读写类】读取指定区域的所有单元格值
    pt_BR: test_get_range_values
  llm: test_get_range_values
parameters:
  - name: address
    type: string
    required: true
    label:
      en_US: address
      zh_Hans: 区域地址
      pt_BR: address
    human_description:
      en_US: address
      zh_Hans: 区域地址，字符串形式，比如：A1:D3
      pt_BR: address
    llm_description: address
    form: llm
  - name: return_excel
    type: select
    required: true
    default: '否'
    label:
      en_US: return_excel
      zh_Hans: 是否返回 Excel 文件
      pt_BR: return_excel
    human_description:
      en_US: return_excel
      zh_Hans: 是否返回 Excel 文件。如果为 是，则接口将额外返回一个 xlsx 文件（文件名.xlsx）
      pt_BR: return_excel
    llm_description: 是否返回 Excel 文件
    form: form
    options:
      - value: '是'
        label:
          en_US: 是
          zh_Hans: 是
      - value: '否'
        label:
          en_US: 否
          zh_Hans: 否
  - name: sheet_name
    type: string
    required: false
    label:
      en_US: sheet_name
      zh_Hans: 操作Sheet页名称
      pt_BR: sheet_name
    human_description:
      en_US: sheet_name
      zh_Hans: 操作Sheet页名称，可选，不填则默认操作当前已激活的Sheet页
      pt_BR: sheet_name
    llm_description: sheet_name
    form: llm
extra:
  python:
    source: tools/test_get_range_values.py
